---
title: "twitter-shiny"
author: "Caleb Trujillo"
date: "1/24/2021"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library('rtweet') ; library('tidyverse') ; library('syuzhet') ;library('emo') ; library('wordcloud') ; library('DT')
```

This R Markdown document is made interactive using Shiny. 


```{r load data, eval = TRUE, include=FALSE}
tweets <- search_tweets(q = "#rstats", 
                        n = 100,
                        include_rts = FALSE,
                        `-filter` = "replies") #%>%
  #mutate(favorite_count = as.numeric(favorite_count), 
         #retweet_count = as.numeric(retweet_count))
         
                        
user_timeline  <- get_timeline("RLadiesSeattle", n = 900)

user_favs  <- get_favorites("RLadiesSeattle", n = 900)

user_friends <- get_friends("RLadiesSeattle")
```

```{r load Rdata, eval = FALSE, include=FALSE}
load("~/workspace/Twitter-shiny/.RData")
```
## Twitter data {.tabset}

### Recent Rstats tweets

The plot below shows time series of #rstats tweets based upon county and favorite count.

```{r tweets, echo=FALSE}
inputPanel(
  selectInput("tweetlang", label = "Language of tweets:",
              choices = unique(tweets$lang), selected = "en", multiple = TRUE)
)


renderPlot({
  ts_plot(tweets %>% filter(lang %in% input$tweetlang) , by = "hours", col = "blue")
})

renderDataTable({
  tweets %>% 
    filter(lang %in% input$tweetlang) %>% 
    select(screen_name,text,lang,favorite_count,retweet_count)
})
```


### Tweets from RL


